### ISSUE TITLE
JavaScript events stop working

### ISSUE THREAD

**Issue by TimMakins** [firebug/firequery#11]
Hi - I noticed this review on
## https://addons.mozilla.org/en-us/firefox/addon/firequery/

Cause some conflicts Rated 1 out of 5 stars

by TomaszKane on March 6, 2015 · permalink · translate

Kubuntu 14.02, Firefox 36, Firebug 2.0.8 and FireQuery 1.4.1
## When I open Firebug JavaScript events stop working. After disable FireQuery problem gone.

and I found the same. I am using Firefox 37.0.1 and Firebug 2.08 and
FireQuery 1.4.1 on Windows 7 64bit.

Regards, Tim Makins

**Comment by aliuk2012** [comment]
Hi @TimMakins, Thanks for the report but this repository etc relate to the FireQuery 2.0. The version you are using is no longer being maintained as it was originally developed by a third party developer who isn't actively developing it. The Firebug Working Group has spoken to the original Creator and have approval to continue with the his idea of Firequery but the Group would now be responsible for maintaining future versions.

Could I suggest you possibly download and install this version that is here on GitHub? If you have any questions or issues please feel free to raise them here.

**Comment by TimMakins** [comment]
Thanks for your speedy reply. I would suggest 2 things:
1/ That you mention on page 'https://github.com/firebug/firequery' that your software is called 'FireQuery 2.0', and that use of v1.0 is not recommended.
2/ That you ask whoever maintains the pages with v1 downloads to remove them.

**Comment by janodvarko** [comment]
> 1/ That you mention on page 'https://github.com/firebug/firequery' that your software is called 'FireQuery 2.0', and that use of v1.0 is not recommended.

Done

> 2/ That you ask whoever maintains the pages with v1 downloads to remove them.

As soon as FQ2 is on AMO the page will be updated

Thanks for the feedback!
Honza
