### ISSUE TITLE
See "Data" in HTML View

### ISSUE THREAD

**Issue by FlashJunior** [firebug/firequery#2]
Are there plans to develop that?

Like it was in [binaryage's firequery Plugin](https://github.com/binaryage/firequery)
![image](https://cloud.githubusercontent.com/assets/58175/6646403/c9eed2be-c9c4-11e4-91cf-3392f484093c.png)

**Comment by janodvarko** [comment]
Yes, it's actually already working, but some clean up is yet necessary (the way how it's displayed)
Anyway,  see the attached screenshot

![firequery](https://cloud.githubusercontent.com/assets/37785/6667188/c45bd4d2-cbea-11e4-8252-cde12ec5e16c.png)

You can try it on your machine, clone the repo and run

```
git clone https://github.com/firebug/firequery.git
cd firequery
jpm run
```

Or generate XPI

```
jpm xpi
```

Honza

**Comment by FlashJunior** [comment]
hmmm.. i did that but can't see it :-/

OSX 10.10, Firefox 36.0.1, Firebug 2.0.8
I see it's installed:
![image](https://cloud.githubusercontent.com/assets/58175/6671036/d09cfaa6-cc02-11e4-9df1-bc265076128b.png)

I restartet Firefox and tried http://firequery.binaryage.com/test/. That's what i see:
![image](https://cloud.githubusercontent.com/assets/58175/6671074/23b44488-cc03-11e4-9356-d79da318fec9.png)

![image](https://cloud.githubusercontent.com/assets/58175/6671222/2c0e367e-cc04-11e4-8c0a-37640b3d696f.png)

**Comment by janodvarko** [comment]
You need Firebug 3 (aka Firebug.next) at this moment (won't be needed in the end).
https://github.com/firebug/firebug.next/releases

Does it work?

Honza

**Comment by FlashJunior** [comment]
No :-/ i installed Firebug 3.0.0 alpha 9.
![image](https://cloud.githubusercontent.com/assets/58175/6677633/2bf56166-cc32-11e4-9a86-c12c5b5e1d85.png)

i also tried Firefox Aurora 38.0a2 with Firebug 3.0.0 alpha 9 - the same :-/

**Comment by janodvarko** [comment]
Weird, works for me (OSX, Firebug 3a9, Firefox 38).

If you go to the Console panel, do you see 'jQuery' logs? Please try to refresh the page after opening the Toolbox.

Honza

**Comment by FlashJunior** [comment]
we can do a teamviewer session if it helps. yes, i tried reloading the page with open panal. stilll the same. no, i just see normal console logs with objects.

**Comment by janodvarko** [comment]
> we can do a team viewer session

Yes please. But, I don't have team viewer. can we just use G+ hangout?

Honza

**Comment by FlashJunior** [comment]
martin.bommeli@gmail.com (will delete this post laster)

**Comment by janodvarko** [comment]
Just for the record, the problem found on G+ hangout....

Updated installations steps (don't forget npm install):

```
git clone https://github.com/firebug/firequery.git
cd firequery
npm install
jpm run
```

Or you can read: https://github.com/firebug/firequery/wiki/Developer-Guide

Honza
