### ISSUE TITLE
Inspector DOM Tree curruption.

### ISSUE THREAD

**Issue by Spown** [firebug/firequery#22]
I don't know why or how, but when FireQuery is enabled some elements in the DOM tree can't be unfolded  or rather they appear empty when unfolded despite having inner html. The common thing about these elements is they all are being processed with JQ. I've noticed that it sometimes works correctly on the first page inspection in a session but after a page reload the problem persists.

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2015-07/2015-07-02_19-53-45.png)

Disabling the extension removes the issue. I know its only a beta, but its a pretty major flaw.

**Comment by aliuk2012** [comment]
Thank you for the report, we will have a look into it.

Could you provide us with more details like what version of Firefox and Operating System you using? If possible do you have a site or demo we could use to replicate the fault?

**Comment by Spown** [comment]
this page is using JQ 1.10.2 and JQ.ui 1.10.4

**Comment by aliuk2012** [comment]
Thanks for that extra info but we still need to know what version of Firefox and Operating System you are using. I've tried on a Mac OS, Firefox Nightly and it works fine. Depending on the version of firefox you are using it might be a backwards compatibility issue which we should be able to resolve if we can replicated it.

**Comment by Spown** [comment]
FF 38.0.5, Win 7 Pro x64
Extensions:
ADB Helper
Adblock Plus
Base64 ⇒ Encoder
Case Changer
ChatZilla
Classic Theme Restorer
ColorZilla
Context Highlight
DownThemAll!
DragIt
Element Hiding Helper for Adblock Plus
FireFTP
FoxyProxy Standard
Go-Mobile
Greasemonkey
HostAdmin
iMacros for Firefox
Image Search Options
JS Deminifier
JSONView
Local Filesystem Links
Open Profile Folder
Russian Hunspell spellchecking dictionary
Saved Password Editor
Session Manager
Simple Locale Switcher
Status-4-Evar
Tab Mix Plus
Toolbar Buttons
Transliterator
Valence

**Comment by Spown** [comment]
I've updated FF to 39 and it got even worse - not even the outer tag is visible:
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2015-07/2015-07-03_00-11-32.png)

**Comment by janodvarko** [comment]
This sounds like a blocker indeed!

Can you please provide detailed instructions how to reproduce the problem?
What URL should we load and what element within that page should we observe?

Thanks!
Honza

**Comment by janodvarko** [comment]
I did some changes, it isn't finished, but do you already see some improvements in the behavior?

Honza

**Comment by Spown** [comment]
Yes, looks like it helped. Thanks!

**Comment by Spown** [comment]
now I get `TypeError: elem.dispatchEvent is not a function firequery-actor.js line 297 > eval:59:6`
I guess it could be a new issue but since firequery-actor.js is one of the files you fixed  for this ticket - it could be related. 

Unfortunately I can't demonstrate this behavior live because it occurs in the Drupal control panel overlay and it would require giving you access to the admin area...

**Comment by janodvarko** [comment]
@Spown: I have done quite a lot of changes and I'd be interested whether it helps.

I also loaded your page, search for bc_span_titles and saw jQuery data associated with it.
Btw. I don't see any data associated with  .bc_outer_wrapper

Can you please retest?

Also, what are the steps to see the elem.dispatchEvent is not a function

Honza

**Comment by janodvarko** [comment]
FireQuery 2 beta 3 has been released
does it fix the problem for you?

https://github.com/firebug/firequery/releases/tag/firequery-2.0.0-beta.3

Honza

**Comment by janodvarko** [comment]
This is the very last xpi release (originally for #25), but it could also fix this bug
http://softwareishard.com/temp/firequery/firequery-2.0.0-beta.4.issue25.xpi

If you have time, can you check it out and let me know if it fixes your problem?

Thanks
Honza

**Comment by Spown** [comment]
I kinda switched back to firebug for a time being, sorry... Its hard to work and debug tools at the same time... I tried the latest build and it seems everything is ok now.

Thank you for your determination and hard work,
Spown

**Comment by janodvarko** [comment]
There is a new version (beta 7)
https://github.com/firebug/firequery/releases/tag/firequery-2.0.0-beta.7

It has another fix that could help to solve this issue.

Can you give it a try?

Honza

**Comment by janodvarko** [comment]
There have been many changes (on both the platform and this extension), is this still a problem?
The current latest is 2.0.1
https://addons.mozilla.org/cs/firefox/addon/firequery/

Honza
