### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by haayman** [firebug/firequery#23]
Hi,

The first line in the wiki: 'Install FireQuery'. But how??? I've downloaded the zip. What should I do with this? Copy the contents somewhere? Could you please explain?

Arjen Haayman

**Comment by janodvarko** [comment]
Hi you need to generate .xpi file. Consequently if you drag-drop the .xpi file onto a Firefox window you'll see and add-on installation dialog.

I don't know how familiar you are with JPM, but you can follow these instructions:
https://github.com/firebug/firequery/wiki/Developer-Guide

and generate the .xpi file by executing jpm xpi in step 4.

If the instructions don't work for you I can generate the xpi for you.

Honza

**Comment by haayman** [comment]
Hi Honza,

Is it not possible to make the xpi available directly?
I have no idea where to issue those commands. In a linux shell? I have no
npm or Mozilla development environment.

Arjen

On Fri, Jul 3, 2015 at 1:37 PM, Jan Odvarko notifications@github.com
wrote:

> Hi you need to generate .xpi file. Consequently if you drag-drop the .xpi
> file onto a Firefox window you'll see and add-on installation dialog.
> 
> I don't know how familiar you are with JPM, but you can follow these
> instructions:
> https://github.com/firebug/firequery/wiki/Developer-Guide
> 
> and generate the .xpi file by executing jpm xpi in step 4.
> 
> If the instructions don't work for you I can generate the xpi for you.
> 
> Honza
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firebug/firequery/issues/23#issuecomment-118323856.

## 

[image: Linkedin] http://nl.linkedin.com/in/haayman [image: Twitter]
https://twitter,com/haayman [image: Facebook]
http://www.facebook.com/haayman [image: Telegram]
http://telegram.me/haayman

**Comment by janodvarko** [comment]
Sure.

I've made a new beta 2 release, see here:
https://github.com/firebug/firequery/releases

The download link under the release will be live in 20-30 min.
(let me know if not)

Honza

**Comment by haayman** [comment]
The installation worked fine, but I don't see any 'data' attached to the elements like in the screenshots?

**Comment by janodvarko** [comment]
I updated the screenshot.
https://github.com/firebug/firequery/wiki

The data are not rendered directly within the panel, but you should see a little icon (an envelope) that indicates its presence. Clicking on the icon shows details...

Does it work for you?

Honza

**Comment by haayman** [comment]
I will let you know next Tuesday when I open up my laptop again :-)

Thanx so far
Op 3 jul. 2015 15:48 schreef "Jan Odvarko" notifications@github.com:

**Comment by janodvarko** [comment]
Alright then,
have a nice weekend :-)

Honza

**Comment by haayman** [comment]
Hi Jan,

Alas, no envelopes. There is an options-page, so the plugin is active.
Otherwise I don't see any presence of the plugin. Is there some place where
I can see log-messages?

​

**Comment by janodvarko** [comment]
> There is an options-page, so the plugin is active.

What options page do you have in mind?

To check whether the plugin is properly installed open about:addons page
(Firefox Menu -> Tools -> Add-ons)
The plugin should be in the list and enabled.

What Firefox version and OS do you use?

Also here is my test page:
http://softwareishard.com/temp/firequery/test1/index.html

If you load the page and select the Inspector panel, you should see an envelop next to e.g. "#my-span" element.

If you select the Console panel and click the "Log data" button on the page you should see jQuery log in the console.

If none of those things work open the Browser Console and let me know if you see any errors.

Btw. you don't need Firebug installed.

Honza

**Comment by haayman** [comment]
The options page belonging to the addon. Where you cat set things like
jQueryURL or useLint.

I'm running FF 39 on windows 8.1

Nope, no envelopes on the elements. No error-messages in the console.
Nothing.
Maybe you can take a look using teamviewer?

Arjen
​

**Comment by janodvarko** [comment]
> Maybe you can take a look using teamviewer?

Yeah, let's try it. Tomorrow would be fine for you?
What time zone are you based  in?

Honza

**Comment by haayman** [comment]
Tomorrow is fine. I'm in Europe/Amsterdam
Op 7 jul. 2015 17:54 schreef "Jan Odvarko" notifications@github.com:

> > Maybe you can take a look using teamviewer?
> 
> Yeah, let's try it. Tomorrow would be fine for you?
> What time zone are you based in?
> 
> Honza
>

**Comment by janodvarko** [comment]
Hi,
can we use G+ hangout?

I don't have teamviewer....

Honza

**Comment by haayman** [comment]
Is it possible to share screen?

On Wed, Jul 8, 2015 at 3:04 PM, Jan Odvarko notifications@github.com
wrote:

> Hi,
> can we use G+ hangout?
> 
> I don't have teamviewer....
> 
> Honza
> 
> On Tue, Jul 7, 2015 at 5:58 PM, haayman notifications@github.com wrote:
> 
> > Tomorrow is fine. I'm in Europe/Amsterdam
> > Op 7 jul. 2015 17:54 schreef "Jan Odvarko" notifications@github.com:
> > 
> > > > Maybe you can take a look using teamviewer?
> > > 
> > > Yeah, let's try it. Tomorrow would be fine for you?
> > > What time zone are you based in?
> > > 
> > > Honza
> > > 
> > > On Mon, Jul 6, 2015 at 9:48 AM, haayman notifications@github.com
> > > wrote:
> > > 
> > > > The options page belonging to the addon. Where you cat set things
> > > > like
> > > > jQueryURL or useLint.
> > > > 
> > > > I'm running FF 39 on windows 8.1
> > > > 
> > > > Nope, no envelopes on the elements. No error-messages in the console.
> > > > Nothing.
> > > > Maybe you can take a look using teamviewer?
> > > > 
> > > > Arjen
> > > > 
> > > > ​
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/firebug/firequery/issues/23#issuecomment-118761527
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/firebug/firequery/issues/23#issuecomment-119247082
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/firebug/firequery/issues/23#issuecomment-119248214.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firebug/firequery/issues/23#issuecomment-119571260.

## 

[image: Linkedin] http://nl.linkedin.com/in/haayman [image: Twitter]
https://twitter,com/haayman [image: Facebook]
http://www.facebook.com/haayman [image: Telegram]
http://telegram.me/haayman

**Comment by janodvarko** [comment]
yes

**Comment by haayman** [comment]
arjen.haayman@gmail.com

On Wed, Jul 8, 2015 at 3:13 PM, Jan Odvarko <notifications@github.com>
wrote:

> yes
>
>
>
> > On 08 Jul 2015, at 15:12, haayman <notifications@github.com> wrote:
> >
> > Is it possible to share screen?
> >
> > On Wed, Jul 8, 2015 at 3:04 PM, Jan Odvarko <notifications@github.com>
> > wrote:
> >
> > > Hi,
> > > can we use G+ hangout?
> > >
> > > I don't have teamviewer....
> > >
> > > Honza
> > >
> > >
> > >
> > > On Tue, Jul 7, 2015 at 5:58 PM, haayman <notifications@github.com>
> wrote:
> > >
> > > > Tomorrow is fine. I'm in Europe/Amsterdam
> > > > Op 7 jul. 2015 17:54 schreef "Jan Odvarko" <notifications@github.com
> >:
> > > >
> > > > > > Maybe you can take a look using teamviewer?
> > > > >
> > > > > Yeah, let's try it. Tomorrow would be fine for you?
> > > > > What time zone are you based in?
> > > > >
> > > > > Honza
> > > > >
> > > > >
> > > > > On Mon, Jul 6, 2015 at 9:48 AM, haayman <notifications@github.com>
> > > > wrote:
> > > > >
> > > > > > The options page belonging to the addon. Where you cat set things
> > > like
> > > > > > jQueryURL or useLint.
> > > > > >
> > > > > > I'm running FF 39 on windows 8.1
> > > > > >
> > > > > > Nope, no envelopes on the elements. No error-messages in the
> console.
> > > > > > Nothing.
> > > > > > Maybe you can take a look using teamviewer?
> > > > > >
> > > > > > Arjen
> > > > > >
> > > > > > ​
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > https://github.com/firebug/firequery/issues/23#issuecomment-118761527
> > > > >.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/firebug/firequery/issues/23#issuecomment-119247082
> > > >.
> > > >
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/firebug/firequery/issues/23#issuecomment-119248214>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/firebug/firequery/issues/23#issuecomment-119571260
> >.
> > >
> >
> >
> >
> > --
> >
> > [image: Linkedin] <http://nl.linkedin.com/in/haayman> [image: Twitter]
> > <https://twitter,com/haayman> [image: Facebook]
> > <http://www.facebook.com/haayman> [image: Telegram]
> > <http://telegram.me/haayman>
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/firebug/firequery/issues/23#issuecomment-119574235>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebug/firequery/issues/23#issuecomment-119574413>.
>



-- 

[image: Linkedin] <http://nl.linkedin.com/in/haayman> [image: Twitter]
<https://twitter,com/haayman> [image: Facebook]
<http://www.facebook.com/haayman> [image: Telegram]
<http://telegram.me/haayman>

**Comment by aliuk2012** [comment]
@janodvarko I can join too if you need me. I'm on G+

**Comment by janodvarko** [comment]
Problem solved, closing this report.

Just for the record: FireQuery 2.0 is for "Native Firefox Developer Tools"
not for Firebug 2.0

Honza

**Comment by haayman** [comment]
Hi Jan,

Is see an envelope in version 3, but there's no popup anymore when I hover it.

**Comment by janodvarko** [comment]
Do you see a popup if you click on the envelope?
Honza

**Comment by haayman** [comment]
Nope
Op 9 jul. 2015 14:44 schreef "Jan Odvarko" notifications@github.com:

**Comment by janodvarko** [comment]
What version of Firefox do you use?
Honza

**Comment by janodvarko** [comment]
Ah, 39, correct?

**Comment by haayman** [comment]
yup

On Thu, Jul 9, 2015 at 2:48 PM, Jan Odvarko notifications@github.com
wrote:

> Ah, 39, correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firebug/firequery/issues/23#issuecomment-119950788.

## 

[image: Linkedin] http://nl.linkedin.com/in/haayman [image: Twitter]
https://twitter,com/haayman [image: Facebook]
http://www.facebook.com/haayman [image: Telegram]
http://telegram.me/haayman

**Comment by janodvarko** [comment]
I have fixed one backward compatibility problem with Fx39 couple of hours ago.

Can you install the following version (it'll soon become beta 4) and let me know if it helps?
http://softwareishard.com/temp/firequery/firequery-2.0.0-beta.3.issue23.xpi

Honza

**Comment by haayman** [comment]
Yes. Fixed. Thanks!

On Thu, Jul 9, 2015 at 2:54 PM, Jan Odvarko notifications@github.com
wrote:

> I have fixed one backward compatibility problem with Fx39 couple of hours
> ago.
> 
> Can you install the following version (it'll soon become beta 4) and let
> me know if it helps?
> http://softwareishard.com/temp/firequery/firequery-2.0.0-beta.3.issue23.xpi
> 
> Honza
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/firebug/firequery/issues/23#issuecomment-119952395.

## 

[image: Linkedin] http://nl.linkedin.com/in/haayman [image: Twitter]
https://twitter,com/haayman [image: Facebook]
http://www.facebook.com/haayman [image: Telegram]
http://telegram.me/haayman
