### ISSUE TITLE
"data" not showing in "inspector" when added later

### ISSUE THREAD

**Issue by FlashJunior** [firebug/firequery#3]
Tested with:
OSX 10.10, Firefox 36.0.1, Firebug 3.0.0 a9, Firequery 2.0.0 b1

**Test 1:**
- go to http://firequery.binaryage.com/test/
- open firebug "inspector tab"
- reload page

now you can see some data infos
- klick on Button "Add H1 data" on the testpage

now you still see the same data infos. h1 still has no data showing. if you do a console log `console.log($("h1").data())` you see it was added correctly.

**Test 2:**
- go to http://firequery.binaryage.com/test/
- open firebug "command editor"
- type in `$("h1").data("test2","some data");` an run it
- go to "inspector tab"

now you still see h1 has no Data - but if you do a console log `console.log($("h1").data("test2"))` it's there.

**Comment by FlashJunior** [comment]
Here is an other Testpage: http://www.flashjunior.ch/test/firequery/

**Comment by janodvarko** [comment]
The Inspector panel doesn't display jQuery data for the first time (page reload required). This is covered by issue #8 

The rest should be fixed and will be part of FireQuery 2 beta 2

Thanks for the report!
Honza

**Comment by FlashJunior** [comment]
ok. thx. i'll check that after "FireQuery 2 beta 2" release.

**Comment by janodvarko** [comment]
Great, I'll update this thread as soon as the next beta is out.
Honza

**Comment by FlashJunior** [comment]
thx. looks good in "FireQuery 2.0.0 beta 2"

**Comment by janodvarko** [comment]
Thanks for the update!

Honza
