### ISSUE TITLE
Optimization: send 'data-modified' packets only if needed

### ISSUE THREAD

**Issue by janodvarko** [firebug/firequery#30]
The number or "data-modified" packets sent back to the client (by FireQueryActor) can be relatively big and it would be great if we can reduce the amount somehow.

The primary purpose of these event packets is to update UI of the Inspector panel. Make sure that the 'jquery-data' indicator (a little envelope icon) is created or removed. The Inspector panel usually doesn't display all of the elements and the update is not needed in most cases. So, if we could determine that the element, whose jQuery.data has changed, is actually not visible (or not even "imported" by the client) we don't have to send that data-modified packet at all.

How could we do that?

Honza

**Comment by janodvarko** [comment]
@captainbrosset: can I figure out the following on the back-end (inside an actor)?
- A node isn't visible in the Inspector panel since its parent is closed
- And/or: a node isn't imported on the client and so it can't be visible.

Honza

**Comment by captainbrosset** [comment]
> A node isn't visible in the Inspector panel since its parent is closed

I don't see a way of knowing this from the backend. All the backend knows is whether a node is known or not (i.e. if it has been shown in the UI at least once)

> And/or: a node isn't imported on the client and so it can't be visible.

This, however, you should be able to know on the backend. If `node` is one of the keys of the `walker.this._refMap` map, then the UI has received information about it (or is in the process of receiving info about it).
I think that's a good enough criteria to filter the list of packets down to the bare minimum.

I think the new `walker.has` method I proposed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1182135#c5 would prove useful for this too.

**Comment by janodvarko** [comment]
@captainbrosset: thanks, I have also reported bug for the 'has' method here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1195742
(patch already attached)

Honza
