### ISSUE TITLE
firequery data pop-up should match dev edition dark theme

### ISSUE THREAD

**Issue by jeffgca** [firebug/firequery#33]
Tried out beta 7 today, looks really good but I noticed that the data pop-ups seems to be firebug themed even when dev edition is using the dark theme: 

<img width="622" alt="banners_and_alerts_and_jquery_data_____jquery_api_documentation" src="https://cloud.githubusercontent.com/assets/104315/9506869/5d12a8a6-4bff-11e5-8792-0d220ac395ca.png">

**Comment by janodvarko** [comment]
Light and Dark themes also supported in FBSDK (so, e.g. the DOM panel has it too).
https://github.com/firebug/firebug.sdk/commit/d9b8d88de194b09a2a2ffe446ab113f1205015d6
(in Firebug.sdk module)

![dark](https://cloud.githubusercontent.com/assets/37785/9584431/66a252d4-5011-11e5-8b5f-6ac9715852c0.png)

![light](https://cloud.githubusercontent.com/assets/37785/9584572/23773334-5012-11e5-9e22-7f2b940cb74e.png)

![firebug](https://cloud.githubusercontent.com/assets/37785/9584437/6c5c9658-5011-11e5-8d61-8f6aeaa7b901.png)

Honza

**Comment by jeffgca** [comment]
@janodvarko Looks great!
