### ISSUE TITLE
The Inspector panel doesn't show jQuery data for the first time.

### ISSUE THREAD

**Issue by janodvarko** [firebug/firequery#8]
1. Load http://firequery.binaryage.com/test/
2. Select the Inspector panel 
3. jQuery data are not visible, the page needs to be refreshed.

Honza

**Comment by FlashJunior** [comment]
works for me in "FireQuery 2.0.0 beta 2"

**Comment by janodvarko** [comment]
Thanks for the update, closing ...
Honza
